-- INSERT INTO NOTE_ENTITY(ID, TITLE, CONTENT) VALUES(NOTE_ID_SEQ.nextval, 'Jack note title', 'Short content');
SELECT * FROM NOTE_ENTITY;
-- INSERT INTO NOTE_USERS (ID, USERNAME, PASSWORD ) VALUES (1, 'KAROL', '$2a$10$322BLEWPEMembFd8/ZXfAuwrsnRBVnV9wVyOtG9EkYk481DKLVqRq');
INSERT INTO NOTE_USERS (ID, USERNAME, PASSWORD ) VALUES (NOTE_USERS_ID_SEQ.nextval, 'KAROL', '$2a$10$322BLEWPEMembFd8/ZXfAuwrsnRBVnV9wVyOtG9EkYk481DKLVqRq');